version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: myPassword

  adminer:
    image: adminer
    restart: always
    ports:
     - 5432:5432